# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-03 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='issuebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datefrom', models.DateField(auto_now_add=True, null=True)),
                ('dateto', models.DateField(auto_now_add=True, null=True)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('idissue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.issuebook')),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='profilepic')),
                ('fkidlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.login')),
            ],
        ),
        migrations.CreateModel(
            name='viewbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookno', models.CharField(max_length=50)),
                ('bookname', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('available', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='idpayreg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.register'),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='idbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.viewbook'),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='idreg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.register'),
        ),
    ]
