# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-06 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_auto_20190504_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='dateto',
            field=models.DateField(null=True),
        ),
    ]
